package com.sanprj.healthcareapp.enums;

public enum Speciality {
	CARDIOLOGIST,
	GENERAL_PHYSICIAN,
	DENTIST,
	PULMONOLOGIST,
	ENT,
	GASTRO
}
//CARDIOLOGIST|GENERAL_PHYSICIAN|DENTIST|PULMONOLOGIST|ENT|GASTRO
